/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faCheck,
    faCheckSquare,
    faChevronDown,
    faChevronUp,
    faColumns,
    faEdit,
    faHome,
    faPlus,
    faSave,
    faSearch,
    faSignOutAlt,
    faTable,
    faTachometerAlt,
    faTrash,
    faTrashAlt,
    faUser,
    faNewspaper,
    faMapMarker,
faPhone,
faPhoneAlt
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faEdit,
    faPlus,
    faTrash,
    faSave,
    faCheckSquare,
    faTrashAlt,
    faCheck,
    faHome,
    faSignOutAlt,
    faNewspaper,
    faMapMarker,
    faPhone,
    faPhoneAlt
};
